version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      next:
        patterns:
          - "next"
          - "eslint-config-next"
          - "@next/*"
      trpc:
        patterns:
          - "@trpc/*"
      prisma:
        patterns:
          - "prisma"
          - "@prisma/*"
      dev-dependencies:
        dependency-type: development
        update-types:
          - minor
          - patch

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
